IDTPDashboard.Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using IDTPDashboard.DataAccess.Interface;
using IDTPDashboard.DomainModel.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ChartJSCore.Helpers;
using ChartJSCore.Models;
using IDTPDashboard.Web.Helper;

namespace IDTPDashboard.Web.Controllers
{
    [Authorize()]
    public class DashboardController : Controller
    {
        private readonly IMenu_Repository _repository;
       // private readonly IParticularsRepository _particularsRepository;
        private readonly IIDTPDashboard_Repository _repositoryHRManagement;
       // private readonly IFinance_Repository _repositoryFinance;
       // private readonly ILanding_Repository _repositoryLanding;
      //  private readonly IPR_Repository _repositoryPR;
//        private readonly IFAManagement_Repository _repositoryFAManagement;
        public DashboardController(IMenu_Repository repository,
        IIDTPDashboard_Repository repositoryHRManagement
        )
        {
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
            _repositoryHRManagement = repositoryHRManagement ?? throw new ArgumentNullException(nameof(repositoryHRManagement));
        }
        public async Task<IActionResult> Index()
        {
            var companyName = HttpContext.User.FindFirstValue("Organization");
            List<Menu_Entity> menuList = await _repository.GetAllMenu(companyName);
            return View(menuList);
        }
        #region  PowerDivIndex
        public async Task<IActionResult> PowerDivIndex()
        {
            var companyName = HttpContext.User.FindFirstValue("Organization");
            HRManagement_Entity hRManagement_Entity = await _repositoryHRManagement.GetAllReports(companyName);
            Chart transactionsCountTodayByFI = TransactionsCountTodayByFIPieChart(hRManagement_Entity.TransactionsCountTodayByFIList);
            // Finance_Entity finance_Entity = await _repositoryFinance.GetAllReports(companyName);
            // Chart UtilityWiseTurnover = UtilityWiseTurnoverPieChart(finance_Entity.UtilityWiseTurnoverList.ToList());
            //Chart ExpensevsRevenue = ExpensevsRevenuePieChart(finance_Entity.ExpensevsRevenueList.ToList());
            //Chart ReceivablevsPayable = ReceivablevsPayablePieChart(finance_Entity.ReceivablevsPayableList.ToList());
            // PR_Entity pR_Entity = await _repositoryPR.GetAllReports(companyName);
            // Chart procurementValuebyOffice = ProcurementValuebyOfficePieChart(pR_Entity.ProcurementValuebyOfficeList);
            // FAManagement_Entity fAManagement_Entity = await _repositoryFAManagement.GetAllReports(companyName);
            // Chart fuelWisePowerPlant = FuelWisePowerPlantPieChart(fAManagement_Entity.FuelWisePowerPlantList);

            // Landing_Entity landing_Entity = await _repositoryLanding.GetAllReports();
            // Chart TotalPowerPlants = TotalPowerPlantsPieChart(landing_Entity.TotalPowerPlantList.ToList());
            // Chart TotalInstalledCapacityMW = TotalInstalledCapacityMWPieChart(landing_Entity.TotalInstalledCapacityMWList.ToList());
            // Chart TotalNumberOfUsersByStatus = TotalNumberOfUsersByStatusBarChart(landing_Entity.TotalNumberOfUsersByStatusesList.ToList());
            // Chart TotalExpenceRevenues = TotalExpenceRevenuesPieChart(landing_Entity.TotalExpenceRevenuesList.ToList());
            // Chart APPUtilizedUnutilized = APPUtilizedUnutilizedPieChart(landing_Entity.appUtilizedUnutilizedList.ToList());
            // Chart AccReceivableAndPayable = AccReceivableAndPayableBarChart(landing_Entity.AccReceivableAndPayableList.ToList());
            // Chart FinancialPosition = FinancialPositionBarChart(landing_Entity.FinancialPositionList.ToList());
             List<Menu_Entity> menuList = await _repository.GetAllMenu(companyName);
            // List<Particular> particulars = await _particularsRepository.GetParticulars(companyName);

            ViewData["transactionsCountTodayByFI"] = transactionsCountTodayByFI;
            // ViewData["UtilityWiseTurnover"] = UtilityWiseTurnover;
            // ViewData["procurementValuebyOffice"] = procurementValuebyOffice;
            // ViewData["TotalPowerPlants"] = TotalPowerPlants;
            // ViewData["TotalInstalledCapacityMW"] = TotalInstalledCapacityMW;
            // ViewData["TotalNumberOfUsersByStatus"] = TotalNumberOfUsersByStatus;
            // if (particulars.Count > 0)
            // {
            //     ViewData["ParticularsDate"] = particulars[0].LastUpdatedDate.ToString("dd-MMM-yy");
            //     ViewData["particulars"] = particulars;
            // }           
            // ViewData["totalNumberOfUsersByStatus"] = landing_Entity.TotalNumberOfUsersByStatusesList.ToList();
            // ViewData["TotalExpenceRevenues"] = TotalExpenceRevenues;
            // ViewData["APPUtilizedUnutilized"] = APPUtilizedUnutilized;
            // ViewData["fuelWisePowerPlant"] = fuelWisePowerPlant;
            // ViewData["AccReceivableAndPayable"] = AccReceivableAndPayable;
            // ViewData["FinancialPosition"] = FinancialPosition;

            return View(menuList);
        }
        private Chart TransactionsCountTodayByFIPieChart(List<TransactionsCountTodayByFI> transactionsCountTodayByFI)
        {
            string[] colorList = ChartHelper.GetColorList();
            List<double?> countValue = transactionsCountTodayByFI.Select(e => Convert.ToDouble(e.totalemployee)).Cast<double?>().ToList();
            List<ChartColor> backgroundColorList = new List<ChartColor>();

            foreach (var item in colorList.Take(countValue.Count()))
            {
                backgroundColorList.Add(ChartColor.FromHexString(item));
            }

            List<string> Lables = transactionsCountTodayByFI.Select(e => e.Organization).ToList();
            PieDataset dataset = new PieDataset()
            {
                Label = "Number of Employees",
                BackgroundColor = backgroundColorList,
                HoverBackgroundColor = backgroundColorList,
                Data = countValue
            };
            return ChartHelper.GeneratePieChart(Lables, dataset);
        }
        private Chart UtilityWiseTurnoverPieChart(List<UtilityWiseTurnover> utilityWiseTurnover)
        {
            string[] colorList = ChartHelper.GetColorList();
            List<double?> countValue = utilityWiseTurnover.Select(e => Convert.ToDouble(e.Turnover)).Cast<double?>().ToList();
            List<ChartColor> backgroundColorList = new List<ChartColor>();

            foreach (var item in colorList.Take(countValue.Count()))
            {
                backgroundColorList.Add(ChartColor.FromHexString(item));
            }

            List<string> Lables = utilityWiseTurnover.Select(e => e.Organization).ToList();
            PieDataset dataset = new PieDataset()
            {
                Label = "Amount",
                BackgroundColor = backgroundColorList,
                HoverBackgroundColor = backgroundColorList,
                Data = countValue
            };
            return ChartHelper.GeneratePieChart(Lables, dataset);
        }
        private Chart TotalPowerPlantsPieChart(List<TotalPowerPlant> totalPowerPlant)
        {
            string[] colorList = ChartHelper.GetColorList();
            List<double?> countValue = totalPowerPlant.Select(e => Convert.ToDouble(e.Number)).Cast<double?>().ToList();
            List<ChartColor> backgroundColorList = new List<ChartColor>();

            foreach (var item in colorList.Take(countValue.Count()))
            {
                backgroundColorList.Add(ChartColor.FromHexString(item));
            }

            List<string> Lables = totalPowerPlant.Select(e => e.Type).ToList();
            PieDataset dataset = new PieDataset()
            {
                Label = "Number",
                BackgroundColor = backgroundColorList,
                HoverBackgroundColor = backgroundColorList,
                Data = countValue
            };
            return ChartHelper.GeneratePieChart(Lables, dataset);
        }
        private Chart TotalInstalledCapacityMWPieChart(List<TotalInstalledCapacityMW> totalInstalledCapacityMW)
        {
            string[] colorList = ChartHelper.GetColorList();
            List<double?> countValue = totalInstalledCapacityMW.Select(e => Convert.ToDouble(e.InstalledCapacityMW)).Cast<double?>().ToList();
            List<ChartColor> backgroundColorList = new List<ChartColor>();

            foreach (var item in colorList.Take(countValue.Count()))
            {
                backgroundColorList.Add(ChartColor.FromHexString(item));
            }

            List<string> Lables = totalInstalledCapacityMW.Select(e => e.Type).ToList();
            PieDataset dataset = new PieDataset()
            {
                Label = "Number",
                BackgroundColor = backgroundColorList,
                HoverBackgroundColor = backgroundColorList,
                Data = countValue
            };
            return ChartHelper.GeneratePieChart(Lables, dataset);
        }
        private Chart TotalNumberOfUsersByStatusBarChart(List<TotalNumberOfUsersByStatus> totalNumberOfUsersByStatus)
        {
            List<double?> EmployeeCount = totalNumberOfUsersByStatus.Select(e => Convert.ToDouble(e.EmployeeCount).ConvertThousand()).Cast<double?>().ToList();
            List<string> Lables = totalNumberOfUsersByStatus.Select(e => e.Type).ToList();
            BarDataset dataset1 = new BarDataset()
            {
                Label = "Number of Posts",
                Data = EmployeeCount,
                BackgroundColor = new List<ChartColor>
                {
                    ChartColor.FromHexString("#01B8AA"),
                },
                BorderColor = new List<ChartColor>
                {

IDTPDashboard.Web/Controllers/IDTPChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ChartJSCore.Helpers;
using ChartJSCore.Models;
using IDTPDashboard.DataAccess.Interface;
using IDTPDashboard.DataAccess.Repositoty;
using IDTPDashboard.DomainModel.Common;
using IDTPDashboard.DomainModel.Entity;
using IDTPDashboard.Web.Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IDTPDashboard.Web.Controllers
{
    //[Authorize()]
    public class IDTPChartController : Controller
    {
        private readonly IIDTPDashboard_Repository _repositoryHRManagement;

        public IDTPChartController(
            IIDTPDashboard_Repository repositoryHRManagement)            
        {
            _repositoryHRManagement = repositoryHRManagement ?? throw new ArgumentNullException(nameof(repositoryHRManagement));
        }
        

        #region  IDTPDashboard1
        public async Task<IActionResult> IDTPDashboard1()
        {
            var Organization = "IDTP";//HttpContext.User.FindFirstValue("Organization");

            HRManagement_Entity hRManagement_Entity = await _repositoryHRManagement.GetAllReports(Organization);            

            long TotalNumberOfUsers = hRManagement_Entity.TotalNumberOfUsersList.FirstOrDefault().totalemployee;
            ViewData["totalemployee"] = Convert.ToDecimal(TotalNumberOfUsers).ToString("#,##0");
            // //JS Chartjs
            ViewData["totalEmpUtilityWise"] = hRManagement_Entity.TransactionsCountTodayByFIList;
            ViewData["rtpStatusByFIs"] = hRManagement_Entity.RTPStatusByFIList;
            ViewData["totalRegisteredUserbyFI"] = hRManagement_Entity.RegisteredUsersByFIList;
            ViewData["netDebitCapPositionByFI"] = hRManagement_Entity.NetDebitCapPositionByFIList;
            ViewData["transactionsAmountTodayByFI"] = hRManagement_Entity.TransactionsAmountTodayByFIList;
            ViewData["transactionAmountBySettlementCycleId"] = hRManagement_Entity.TransactionAmountBySettlementCycleIdList;
            ViewData["transactionsSettledUnsettledPieChart"] = hRManagement_Entity.TransactionsSettledUnsettledList;
            ViewData["transactionCountByTypePieChart"] = hRManagement_Entity.TransactionCountByTypeList;
            ViewData["transactionCountBySettlementTime"] = hRManagement_Entity.TransactionCountBySettlementTimeList;
            ViewData["failedTransactionCountByFI"] = hRManagement_Entity.FailedTransactionCountByFIList;
            
            return View();
        }
        #endregion
    }
}

IDTPDashboard.Web/Views/Shared/Site/_Config.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

<script>
    const appsetting = {
        apiurl:@Json.Serialize(@Configuration.GetSection("ApiUrls").GetSection("commonUrl").Value)
    }

</script>

IDTPDashboard.Web/Views/Shared/Site/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>IDTP Dashboard</title>


    <!-- Custom fonts for this theme -->
    <link href="~/theme/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="~/theme/css/freelancer.min.css" rel="stylesheet">
    <link href="~/css/theme_custom.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="https://fonts.maateen.me/bangla/font.css" rel="stylesheet">
    @*<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">*@
    <link href="~/theme/css/custom.css" rel="stylesheet" />
    <link href="~/lib//chart.js/Chart.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/dataTables.bootstrap4.css" rel="stylesheet" />
    <!-- Developd by Md.Istiak Alam-->
    <script src="~/theme/vendor/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.js"></script>

    <script src="~/theme/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="~/theme/vendor/jquery-easing/jquery.easing.min.js"></script>

    <script src="~/theme/js/jqBootstrapValidation.js"></script>
    <script src="~/theme/js/contact_me.js"></script>
    <script src="~/js/moment.js"></script>
    <script src="~/lib/chart.js/Chart.min.js"></script>
    @*https://emn178.github.io/chartjs-plugin-labels/samples/demo/*@
    <script src="https://cdn.jsdelivr.net/gh/emn178/chartjs-plugin-labels/src/chartjs-plugin-labels.js"></script>
    @*<script src="~/lib/chart.js/chart-plugin.js"></script>*@
    @*<script src="~/theme/js/freelancer.min.js"></script>*@
    <script src="~/js/Vue-js.js"></script>
    <script src="~/js/axios.js"></script>
    <script src="~/js/v-select.js"></script>
    @*<script src="~/theme/js/html2canvas.js"></script>*@
    <script src="~/theme/js/html2pdf.bundle.min.js"></script>
    <script src="~/js/chart-helper.js"></script>
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>

    <style>
        img {
            border-radius: 50%;
        }
    </style>

</head>

<body id="page-top">
    <!-- Navigation -->
    <partial name="~/Views/Shared/Site/_Navbar.cshtml" />
    <!--Navbar -->

    <div class="container-fluid">
        @RenderBody()
    </div>
    <!--Pages end-->

    @RenderSection("Scripts", required: false)
    <partial name="~/Views/Shared/Site/_Config.cshtml" />
</body>
</html>

IDTPDashboard.Web/Views/Shared/Site/_Navbar.cshtml
@using System.Security.Claims;
@{ 
    var OrgName = Context.User.FindFirstValue("Organization");
    if (OrgName == "IDTP")
    {
        OrgName = "Bangladesh Bank";
    }

}
<nav class="navbar navbar-expand-lg fixed-top background-color:#1779ba;" style="background-color: #1A6BA0;padding-top:5px !important;padding-bottom:5px !important" id="mainNav">
    <div class="row" style="width:100%">
        <div class="col-md-2" style="margin-top:4px">
            @if (Context.User.FindFirstValue("Organization") == "IDTP")
            {
                <a class="form-inline btn btn-link" asp-controller="IDTPChart" asp-action="IDTPDashboard1" style="color:white">
                    <b> <i class="fas fa-home"></i> Home</b>
                </a>
            }
            else
            {
                <a class="form-inline btn btn-link" asp-controller="Dashboard" asp-action="Index" style="color:white">
                    <b> <i class="fas fa-home"></i> Home</b>
                </a>
            }

        </div>
        
        <div class="col-md-7" style="text-align:center">            
            <img src="~/logo//1200px-Government_Seal_of_Bangladesh.svg.png" alt="Italian Trulli" style="width:60px;height:60px;">
            <a class="navbar-brand js-scroll-trigger text-uppercase" href="#" style="font-size:1.30em !important">&nbsp;&nbsp; @OrgName IDTP Executive Dashboard</a>
            <button class="navbar-toggler" style="float:left" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4"
                    aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="col-md-3">
            @if (User.Identity.IsAuthenticated)
            {
                <div class="form-inline" style="float:right;margin-top:13px">
                    <a style="color:white">Hi @User.Identity.Name!</a>&nbsp;&nbsp;&nbsp;
                    <a asp-controller="Account" asp-action="Logout" style="color:white"><b> <i class="fas fa-sign-out-alt"></i>Logout</b></a>
                </div>

            }
        </div>
    </div>

</nav>